import {
  Activity,
  Airplay,
  AlarmClockIcon,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowUp,
  Baby,
  BadgeAlert,
  Bold,
  Bug,
  Calendar,
  CalendarDays,
  Check,
  Settings,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleUserRound,
  Cloud,
  Code,
  Copy,
  Database,
  Ear,
  Fan,
  Flower,
  GalleryHorizontal,
  Github,
  Heart,
  Info,
  Italic,
  Lamp,
  LayoutPanelLeft,
  LifeBuoy,
  LogOut,
  type LucideIcon,
  Mail,
  MenuSquare,
  MessageSquare,
  MoonStar,
  Plus,
  PlusCircle,
  Search,
  Sparkles,
  Star,
  Sun,
  Table,
  Terminal,
  Underline,
  UserPlus,
  Users,
  Wind,
  X,
} from "lucide-react-native";
import { cssInterop } from "nativewind";


function interopIcon(icon: LucideIcon) {
  cssInterop(icon, {
    className: {
      target: "style",
      nativeStyleToProp: {
        color: true,
        opacity: true,
      },
    },
  });
}
interopIcon(Heart);
interopIcon(Settings);
interopIcon(Sun);
interopIcon(MoonStar);
interopIcon(AlignJustify);
interopIcon(Star);
interopIcon(Activity);
interopIcon(Airplay);
interopIcon(AlarmClockIcon);
interopIcon(AlertCircle);
interopIcon(AlignRight);
interopIcon(Baby);
interopIcon(BadgeAlert);
interopIcon(Bug);
interopIcon(Calendar);
interopIcon(CircleUserRound);
interopIcon(Database);
interopIcon(Ear);
interopIcon(Fan);
interopIcon(GalleryHorizontal);
interopIcon(Lamp);
interopIcon(Table);
interopIcon(ArrowDown);
interopIcon(ArrowUp);
interopIcon(ChevronDown);
interopIcon(LayoutPanelLeft);
interopIcon(MenuSquare);
interopIcon(Check);
interopIcon(ChevronsDownUp);
interopIcon(ChevronsUpDown);
interopIcon(Copy);
interopIcon(CalendarDays);
interopIcon(Sparkles);
interopIcon(Bold);
interopIcon(Italic);
interopIcon(Underline);
interopIcon(AlignLeft);
interopIcon(Info);
interopIcon(X);
interopIcon(Search);
interopIcon(ChevronRight);
interopIcon(ChevronLeft);
interopIcon(ChevronUp);
interopIcon(Cloud);
interopIcon(LifeBuoy);
interopIcon(LogOut);
interopIcon(Mail);
interopIcon(MessageSquare);
interopIcon(Plus);
interopIcon(PlusCircle);
interopIcon(UserPlus);
interopIcon(Users);
interopIcon(Wind);
interopIcon(Flower);
interopIcon(AlignCenter);
interopIcon(Terminal);
interopIcon(AlertTriangle);
interopIcon(Code);
interopIcon(CheckSquare);

export {
  Activity,
  Airplay,
  AlarmClockIcon,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowUp,
  Baby,
  BadgeAlert,
  Bold,
  Bug,
  Calendar,
  CalendarDays,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleUserRound,
  Cloud,
  Code,
  Copy,
  Database,
  Ear,
  Fan,
  Flower,
  GalleryHorizontal,
  Heart,
  Info,
  Italic,
  Lamp,
  LayoutPanelLeft,
  LifeBuoy,
  LogOut,
  Settings,
  Mail,
  MenuSquare,
  MessageSquare,
  MoonStar,
  Plus,
  PlusCircle,
  Search,
  Sparkles,
  Star,
  Sun,
  Table,
  Terminal,
  Underline,
  UserPlus,
  Users,
  Wind,
  X,
};
